### ISSUE TITLE
Can I parse HTML5 with this crate?

### ISSUE THREAD

**Issue by untitaker** [RazrFalcon/xmlparser#16]
I've successfully used xmlparser to parse HTML, however I noticed that xmlparser does not accept attributes without quotes (and then some other things). Is this project willing to accept patches that are at least avoiding errors on html5 or is this entirely out of scope?

**Comment by RazrFalcon** [comment]
No. And this is not planed.

AFAIK, HTML5 is far more complex than simply omitting quotes around attribute values. It would be easier to simply fork the xmlparser and add an HTML specific stuff.

**Comment by untitaker** [comment]
thanks, just as an update I have since created https://github.com/untitaker/html5gum which solves my needs.
