### ISSUE TITLE
Access to current depth and text position

### ISSUE THREAD

**Issue by gwenn** [RazrFalcon/xmlparser#24]
I am trying to implement an API similar to [libxml2-xmlreader](https://gnome.pages.gitlab.gnome.org/libxml2/devhelp/libxml2-xmlreader.html) / [xmltextreader](https://learn.microsoft.com/en-us/dotnet/api/system.xml.xmltextreader?view=net-7.0) / [XMLStreamReader](https://www.javadoc.io/static/org.codehaus.woodstox/stax2-api/4.2.1/org/codehaus/stax2/XMLStreamReader2.html) using `xmlparser::Tokenizer`.
But I missing access to current `depth`:
https://github.com/RazrFalcon/xmlparser/blob/7334c08aabd21463507a77a288924ea8587865e4/src/lib.rs#L338
And text position (Tokenizer's `stream.gen_text_pos()`) for error report.
Would you mind giving access to these two states ?
Thanks

**Comment by RazrFalcon** [comment]
`depth` and stream position are internal for a reason. You're not suppose to use/rely on then.
You can keep track of depth on your side and each token already has a position.

**Comment by gwenn** [comment]
[libxml2](https://gnome.pages.gitlab.gnome.org/libxml2/devhelp/libxml2-xmlreader.html#xmlTextReaderDepth) , [csharp](https://learn.microsoft.com/en-us/dotnet/api/system.xml.xmltextreader.depth?view=net-7.0#system-xml-xmltextreader-depth) and [java](https://www.javadoc.io/static/org.codehaus.woodstox/stax2-api/4.2.1/org/codehaus/stax2/XMLStreamReader2.html#getDepth--) give access to current depth.

For text position, I guess I can copy paste https://github.com/RazrFalcon/roxmltree/blob/adec50c7361cf1dfbbea03bc928d1d20728f230d/src/lib.rs#L177-L180

**Comment by gwenn** [comment]
Depth is used when you need to match an `ElementEnd` with an `ElementStart`.
For example, to implement  [xmlTextReaderNext](https://gnome.pages.gitlab.gnome.org/libxml2/devhelp/libxml2-xmlreader.html#xmlTextReaderNext) / [skip](https://learn.microsoft.com/en-us/dotnet/api/system.xml.xmltextreader.skip?view=net-7.0#system-xml-xmltextreader-skip) / [skipElement](https://www.javadoc.io/static/org.codehaus.woodstox/stax2-api/4.2.1/org/codehaus/stax2/XMLStreamReader2.html#skipElement--)
Or [ReadSubtree](https://learn.microsoft.com/en-us/dotnet/api/system.xml.xmlreader.readsubtree?view=net-7.0#system-xml-xmlreader-readsubtree).

Current draft (implemented directly in `xmlparser` crate):
https://github.com/gwenn/xmlparser/blob/1da8b12129b1dd433c78159b3eb9b74dcc6f0837/src/reader.rs#L216-L218

> And text position (Tokenizer's stream.gen_text_pos()) for error report.

(Like `roxmltree`)

**Comment by RazrFalcon** [comment]
>Depth is used when you need to match an ElementEnd with an ElementStart.

You should count this on your side, because entity references could introduce elements as well. The depth `xmlparser` stores is not what you need/want. It shouldn't really be there to begin with.

**Comment by RazrFalcon** [comment]
Simply treat `xmlparser` as a low-level tokenizer. It's not a complete "parser", but a foundation for a parser. So it's perfectly normal to have some wrapper code on your side.

**Comment by gwenn** [comment]
Ok,
I manage to reimplement them on my side (by duplicating `Token::span()`):
https://github.com/gwenn/xmlreader/blob/5248ccd05badd0dd414546b526d91c34ec5e18e7/src/lib.rs#L117-L154
