### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by jdrouet** [RazrFalcon/xmlparser#28]
I'm proposing to put in place some automatic release process using release-plz.

https://github.com/MarcoIeni/release-plz

This tool will automatically detect if there are some breaking changes and therefore if it's a patch, a minor or a major version change.
If it's ok for you, I'll open a PR to implement it.

**Comment by RazrFalcon** [comment]
I'm generally agains any automation. Too flaky. And we have like one release a year anyways.
